[phases.build]
cmds = [
    "mkdir -p storage/framework/{sessions,views,cache/data}",
    "mkdir -p database",
    "touch database/database.sqlite",
    "composer install --no-dev --optimize-autoloader",
    "php artisan migrate --force"
]
